## ---------------------------------------------------------------------------------------------------------------------------------
#| label: replication
#| include: false
#' ---
#' title: "Replication code for 'Paper title'"
#' date: "`r format(Sys.Date(), '%d %B %Y')`"
#' author: Your name
#' ---
#' 
#' Generated by `knitr::spin()` from `code.R`.
#' 
#' You can add any text you want to appear in the replication -- but not in the paper -- in chunks like this.
#' 
#' You can run the replication by executing the lines below
#' 
#' knitr::purl("1_analysis.qmd",  "2_replication_code.R")
#' 
#' knitr::spin("2_replication_code.R")  
#' 
#' ## Set up
#' 



## ---------------------------------------------------------------------------------------------------------------------------------
#| label: setup
#| echo: true
#| eval: true
#| purl: true

pacman::p_load(tidyverse, DeclareDesign, foreign, knitr)

Ys <- c("videoLikep1r", "videoSharep1r", "videoBookmarkp1r", "videoCommentTickedp1r", "watch_percentage_", "skipped_video_")

Y_labels <- c("Like", "Share", "Bookmark", "Comment", "Watch", "Skip")



## ---------------------------------------------------------------------------------------------------------------------------------
#| label: data
#| echo: true
#| eval: true
#| purl: true

# fabricate(N = 100, X = rnorm(N), W = rnorm(N), Y = X + rnorm(N)) |> write.csv("assets/my_data.csv")

df <- read.csv("assets/my_data.csv")



## ---------------------------------------------------------------------------------------------------------------------------------
#| include: false
#' # Figure (title that will appear on replication material)


## ---------------------------------------------------------------------------------------------------------------------------------
#| label: figure
#| fig-cap: "A caption"
#| echo: true
#| eval: true
#| purl: true

figure_1 <-
  df |> 
  ggplot(aes(Y, X)) +
  geom_point() +
  theme_bw()

figure_1  



## ---------------------------------------------------------------------------------------------------------------------------------
#| include: false
#' # Table (title that will appear on replication material)


## ---------------------------------------------------------------------------------------------------------------------------------
#| label: table
#| echo: true
#| eval: true
#| purl: true
#| results: 'asis'

models <-
list(
`this one` = lm_robust(Y ~ X, data = df),
`that one` = lm_robust(Y ~ X + W, data = df)
)

models |> 
  texreg:::htmlreg(include.ci = FALSE)



## ---------------------------------------------------------------------------------------------------------------------------------
save.image("saved/analysis.Rdata")

