---
format: 
   revealjs:
      embed-resources: true
      theme: moon
      slide-level: 3
      slide-number: true
      toc-depth: 2
      show-slide-number: all
      preview-links: auto
      number-sections: true
      link-color: orange
title: "My presentation"
author: "Your name"
bibliography: assets/bib.bib
---



```{r setupp, include = FALSE}
pacman::p_load(DeclareDesign,  knitr, plotly, tidyverse)
theme_set(theme_bw())

# Replicate
# To be fully self contained you can uncomment below and run the analysis file from here:
# knitr::purl("1_analysis.qmd",  "2_replication_code.R")
# knitr::spin("2_replication_code.R")  

load("saved/analysis.Rdata")

```

# Overview

* Questions and Answers
* Data
* Analysis
  * Descriptives
  * Causal Estimates
  * Explanation
* Discussion


## Questions ans answers {.smaller}

* One point
* And another

here is reference; try hovering over it:  @blair2023research

# Tables and Figures

## My figure

```{r}
#| fig-cap: "My figure caption"  
figure_1
```


## My table {.smaller}

```{r}
#| results: 'asis'

cat('<div style="background-color:white; color:black; padding:1em;">')
models |> 
  texreg:::htmlreg(include.ci = FALSE, caption = "Here is a caption for this table")
cat('</div>')

```


# Conclusion

1. this
2. that

# References

