---
title: "Honors 21-22: Welcome"
author: "Macartan Humphreys"
date: "9/13/2021"
output:
  beamer_presentation:
    slide_level: 2
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Our goal

* We want everyone here to write a first rate piece of original, publishable, social scientific research on an important question
* We want everyone here to get honors
* We want you to get a deep understanding of how research is done and a deeper appreciation of how to evaluate research
* We want you to be well and enjoy the research process

## What is a thesis?

* An original piece of research
* Length: 75 pages. In practice 70-150. *Quality trumps quantity.*
* Asks and answers a *well defined question*: it is so important that the question is well defined. A good test is whether, right now, you could imagine, broadly, 3 or 4 different answers to your question but you don't know which one is right.
* A typical structure might look like this (see [\textcolor{orange}{here}](http://macartan.nyc/teaching/how-to-write/)):

    1. Introduction and motivation
    2. Theory: maybe formal, maybe not; hypotheses
    3. Design: what information you will use and how you will use it
    4. Results: basic patterns, main analysis
    5. Going deeper: new  analysis, explorations, or theoretical development
    6. Conclusions

* But there is no fixed structure: it depends on the substance



# Who is responsible for what

## Our roles

Three people are helping you:

* Your adviser
* The instructor and the preceptor 

## Our roles: Your advisor

Your adviser:

* High level substantive guidance. 
* Helps determine the question and strategy. Helps connect with literature.
* Takes part in prospectus defense and thesis defense. 
* Grades the thesis.

* Some read multiple early drafts, some do not.

## Working with your adviser:

* Keep them up to date. Share a folder with them so they can see progress and have everything in one place.
* Be sure they understand the big picture as well as the details.
* Share concise summaries of where you are before meetings. 
* Always identify what you are unhappy with, where you need help
* You do *not* have to follow the advice of your advisor; but:
    * if you don't understand the advice, ask for clarification; repeat back what you think is being suggested
    * if you don't agree push back and argue your position. 
* You should treat them respectfully, and of course, they should also treat you respectfully. If issues arise let us know.
* Address: Different professors prefer different addresses but:
    * a good default is "Dear Professor X." 
    * "Hey" is not a good default.
* Don't ghost

## Our roles: Instructor / Preceptor

* We help with all of that $\uparrow$
* We help navigate research processes and tools
* We give written feedback after the prospectus and thesis defense
* We meet regularly to accompany progress, give guidance and  troubleshoot
* In practice, if appropriate, we sometimes help with coding issues and related. But we try not to do any work that is properly yours! 

## Our roles: you

Besides the interim products, you have two "final" deliverables:

* Class grades depend mainly on the thesis (95%) this is the main deliverable

* There is 5% for a "dissemination project" which might be:

  * A blog post summarizing the work
  * A short article in a college newspaper or elsewhere
  * A journal submission
  * A video summarizing some feature of the work
  * Youtube... Instagram...

## Our role: You 2

* Besides your work on these deliverables you can add a lot by being supportive of each other. 

* Tune in to the projects of others in your small group. Figure out who you might be a special support to.  


## Note on Grades:

* Technically: 
  * Honors grades are awarded by the adviser. 
  * Class grades are awarded by the instructors. 
* In practice these tend to be the same but they do not have to be. The instructor grades are sometimes higher or lower and seek to correct for grading idiosyncrasies.

* If appropriate, Fall grades can be updated based on the fruits of the work, seen in the Spring.

* Thesis grades are based on 31 March version of the thesis (this means that there is time between the defense and the "deposit" to edit). 

## Note on Honors determination:

* A committee in the department makes final determination on honors. 
* This decision is  largely based on the grading of the thesis, as well as GPAs
* More information on honors [\textcolor{orange}{here}](https://polisci.columbia.edu/content/department-honors)


# How we are organized

## Group meetings

* This plenary
* Tomorrow and Wednesday: General methods meetings. 
   * Research design / approaches. 
   * 21 more quantitative
   * 22 more qualitative (process tracing and case selection) 
* Thursday, Friday: Past theses: Come to at least one of these.
* Next: Research tools; IRB processes. Come to one or both of these.

## Small meetings

* We will organize people into 4 groups of 3 or 4
* Every group will have a two hour monthly session. 
* Provide **memos** by the *evening before* your session; save into: `Honors_2021/2 Student folders/Your Name/1 memos`
* Prepare to present your memo for about 10 mins with the aims of communicating to the whole group (a) where you have made progress (b) what challenges you have
* In addition: weekly open office hours 

## Major Deadlines

* 14 April 2021: Public presentation of theses
* **31 March 2021: Theses Due** 
* 21-23 March: 2021: Thesis defense meetings
* 10 March 2021: Draft of complete thesis given to advisers
* 19 February 2021: Drafts of 3 chapters.
* 18 January 2021: Drafts of 2 core chapters.
* 25 November 2020: First draft of "main" chapter (in practice which is written first depends on the project but often writing is best done from the inside out)
* 25-29 October 2020: Design defenses with advisers ("prospectus defense")

## Walk through Drive folder structure

* Google drive is a **file sharing** software that keeps folder synced across computers and users
* Easier to use if you install the **desktop app** rather than using web interface
* Google drive warning: If you put something in everyone can see it; if you delete something everyone loses it; **edit with care**
* If you do not want your work to be shared; or you face capacity constraints with big data files: we can set up individual folders. Let us know.
* Advantage of writing and doing analysis "**live**" is that it is easier for us to give timely feedback; we know where you are on the work at any moment. Very open science. Not for everyone.

## Folder Structure

1. `Resources and readings`
2. `Student folders / your name`
   0. archive 
   1. memos
   2. design
   3. resources
   4. data and analysis
   5. writing
   6. final presentation
3. `Final presentations`
4. `Final theses`
5. `Dissemination projects`


## Miscellaneous

* Research approval, IRBs, ethics
* Funding 

## Being well

* Doing original research can be a huge source of joy.
* It can also be very challenging and very stressful; everyone doing research---*everyone*---goes through stages where they think that they and their work are worth nothing. Reach out if your feel overwhelmed. 
* Communicate with us when you run into problems.


# Your topics

## Now time to hear from you

* say briefly who you are
* describe the **main question** 
* say why it is important
* what other research this connects to 
* how you are thinking about answering the question 
* highlight something about the research that you are still fuzzy on 

* We have 4 minutes each:

## Random order

*	Joyce	Liu
*	Michael	Rubin
*	Zoe	Mavrides
*	Megan	Rodriguez
*	Sarah	Howard
*	Emily	Eget
*	Sydni	Scott
*	Ohad	Klopman
*	William	Todd

## Random order

*	Stephanie	Lai
*	Kerem	Tuncer
*	Molly	Kraus
*	Lorelei Vaisse 
*	Jose 	Ramirez
*	Trey	Sprouse
*	Shelly	Michael
*	Emily	Olson

