---
title: "workflow: some principles"
author: "Macartan Humphreys"
date: "10/5/2020"
output: beamer_presentation
bibliography: bib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Principles

* Always work from a folder where your work automatically backs up.

   * Dropbox, Drive, many others

* Have analysis files integrated with writing files

   * `Rmd` fabulous for this
   * Set it up so that you can quickly do reality checks on data and analysis
  
* Be able to replicate all data work and analysis with one click

* Outsource formatting. 

   * e.g. `tex` and `.Rmd` autimatically format. If you use Word, use their "Styles"
   * Bibliographies: use bibtex or similar. Keep a file and reference like this `@putnam2000bowling` (in Rmd) which produces @putnam2000bowling and handles the formatting. Other tools work similarly. Don't do this by hand.
  
# Folders and files.

* Have all files: writing, files, data files, additional analysis files or images, etc in a single directory with relative references

  * Number your folders. 
  * Have few files in each folder.
  * I label files with date: `20201005_paper.Rmd`
  * Compile regularly and have a readable compiled file beside your work file
  * Keep your main document clean and source in sections/modules; you can turn off sourcing if some segments are giving trouble (see sourcing in the file `1../2_2../Lecture.Rmd`)
  * Have an archive folder `0_archive` and backup old copies regularly (not so important if you have good versioning)
  
# Examples

See examples in `2 Student folders/your name/analysis.Rmd`

# Tasks 

* Keep a to do list
* If you use github it is great to use "issues" to keep track of to dos
* Try to complete well defined tasks in one sitting. Work in chunk.
* If you have a repetitive task there is probably a way to automate it: ask for help
* If you have a conceptually hard task that you are not making progress on, stop, move away, and try it from a whole new angle
* Order your tasks: figure out whether you work better linearly or doing parallel work. 
* Cross off tasks when done
* Don't be afraid to discard work
* Be ambitious but don't let the best be the enemy of the good.

# References
