---
title: "Writing seminar | HU 2024"
format: 
  html:
    theme: slate
    embed-resources: true
---

# Resources

* [Intro slides](https://macartan.github.io/writing_seminar/intro_slides.html)

* [DeclareDesign bootcamp slides](https://macartan.github.io/dd_bootcamp/dd.html)

* [Research design form](https://github.com/macartan/writing_seminar/tree/main)

* Sample project structure in `git` https://github.com/macartan/writing_seminar/tree/main/sample_project


# Goals

Our goal is to write a paper in 6 weeks.  We will have four 5 hour group sessions plus off biweekly individual sessions in alternative weeks.

Complete with the creation of a data archive and, if relevant, a pre-registration.
The assumption is that you do not need to do original data collection in this time frame but you do need to do analysis and writing.

# The plan

Our steps will be:

1. Introduction
    1. Task: Describe the design informally in MIDA terms
    2. Task: Identify relevant literature and a model article
2. Design
   1. Task: Read one piece from relevant literature of at least 2 classmates 
   2. Task: Formally "declare" the design, present the declaration
   3. Task: Situate the contribution, present the contribution
3. Writing from inside out
   1. Task: *Before class*: Only if relevant for your project: register the design before implementing analysis. This is not relevant if you have already implemented analysis. 
   2. Task: *Before class*: Share abstract, introduction, and paper outline, identifying any additional analyses
   3. Task: *In class*: Present *Main Results*, table or figure
5. Draft 1 shared and discussed
   1. Task: *Before class*: Share draft 1
   2. Task: Read draft of at least 2 classmates 
6. Final class presentations
   1. Task: Incorporate comments, complete a draft
   2. Task: Present in class using slides   
